name: Laravel

on: [push, pull_request]

jobs:
  static_analysis:
    name: Static Analysis

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP, Tools and Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2, composer-normalize, php-cs-fixer, phpstan
          extensions: dom, fileinfo, gd, mbstring, xdebug

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Run Composer Validate
        run: composer validate --strict

      - name: Run Composer Normalize
        run: composer-normalize --dry-run

      - name: Run PHPStan
        run: phpstan analyse --memory-limit=-1 -vvv

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run -vvv

  unit_tests:
    name: Laravel ${{ matrix.laravel }} (${{ matrix.os }}, ${{ matrix.php }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        php: ['7.2', '7.3', '7.4', '8.0']
        laravel: ['6.0', '7.0', '8.0']
        exclude:
          - php: '7.2'
            laravel: '8.0'

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP, Tools and Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, phpunit:8.5.13
          extensions: dom, fileinfo, gd, mbstring, xdebug

      - name: Install dependencies
        run: composer update --with illuminate/support:~${{ matrix.laravel }} --no-interaction --no-progress

      - name: Run PHPUnit
        run: phpunit -d memory_limit=-1 -vvv
